### ISSUE TITLE
Rotation fails on Ubuntu 18.04.1 LTS (Bionic Beaver) 

### ISSUE THREAD

**Issue by ddluke** [stefansundin/aws-rotate-key#7]
`aws-rotate-keys` fails on Ubuntu 18.04.1 LTS (Bionic Beaver)  with the following error message:

```
Using access key <AWS_OLD_ACCESS_KEY> from profile "<AWS_PROFILE>".
Your user arn is: <ARN>

You have 1 access key associated with your user:
- <AWS_OLD_ACCESS_KEY> (Active, created <CREATED_TIMESTAMP>, last used <LAST_USED_TIMESTAMP> for service <SERVICE> in <AWS_REGION>)

Do you want to create a new key and deactivate <AWS_OLD_ACCESS_KEY>? [yN] y
Created access key <AWS_NEW_ACCESS_KEY>.
Failed to replace old access key. Aborting.
Please verify that the file <HOME_DIR>/.aws/credentials is formatted correctly.
Deleted access key <AWS_NEW_ACCESS_KEY>.
```

According to colleagues, this issue also appeared on MacOS

**Comment by stefansundin** [comment]
Can you check your `~/.aws/credentials` file and see whether or not the regexes here would match? https://github.com/Fullscreen/aws-rotate-key/blob/d7d551fe440160298880547d6cc6a673c600d01d/main.go#L137-L140

I think an improvement can be made to see if the program can find the current keys in the file first so that this error occurs before even attempting to create a new access key.
